Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Metrics/BlockNesting:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Metrics/ClassLength:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce:
    inject: 'reduce'
    find:
    detect: 'find'

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/EvenOdd:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Style/FileName:
  Enabled: true

Style/FlipFlop:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/InlineComment:
  Enabled: false

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Metrics/MethodLength:
  Enabled: true

Style/ModuleFunction:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/Next:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/OpMethod:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PerlBackrefs:
  Enabled: true

Style/PredicateName:
  NamePrefixBlacklist: []

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

# Lint

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/ConditionPosition:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/InvalidCharacterLiteral:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/Void:
  Enabled: true
