inherit_from:
  - .rubocop.unhound.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
